# Generated by Django 2.0.9 on 2020-03-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rides_offered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='rides_taken',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
