##Circle invitations Models

#Django
from django.db import models
#utilities
from cride.utils.models import UtilsModel
from cride.pharma.manager.invitations import InvitiationManager

class Invitation(UtilsModel):
    """Circle invitation
     A circle invitation is a ramdom text
     that acts as a unique code that grants access to a specifics
     circle.
     this code are generated by users that are already
     members of the circle and have a remaining_invttations
     value greater than 0

    """
    code = models.CharField(max_length=50, unique=True)
    issued_by = models.ForeignKey(
        'users.User',
        on_delete=models.CASCADE,
        help_text='Circle member that is providing the invitation',
        related_name='issued_by'
    )
    used_by= models.ForeignKey("users.User", on_delete=models.CASCADE, null=True, help_text='User that used the code to enter the circle')
    
    circle = models.ForeignKey("pharma.Circle", on_delete=models.CASCADE)
    used = models.BooleanField(default=False)
    used_at = models.DateTimeField(blank=True, null=True)
    objects = InvitiationManager()

    def __str__(self):
        return '#{}: {}'.format(self.circle.slug_name, self.code)
    